#! /bin/sh
 
### BEGIN INIT INFO
# Provides:          logstash
# Required-Start:    $network $remote_fs $named $elasticsearch
# Required-Stop:     $network $remote_fs $named $elasticsearch
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start logstash at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
 
. /lib/lsb/init-functions

name="logstash"
logstash_bin="/opt/logstash/bin/logstash"
logstash_conf="/etc/logstash/logstash.conf"
logstash_log="/var/log/logstash.log"
pid_file="/var/run/logstash.pid"
logstash_opts="-f ${logstash_conf} -l ${logstash_log}"

start () {
        log_daemon_msg "Starting $name" "$name"
        if start-stop-daemon --quiet --oknodo --pidfile "$pid_file" -b -m --exec $logstash_bin --start -- $logstash_opts; then
                log_end_msg 0
        else
                log_end_msg 1
        fi
}
 
stop () {
        log_daemon_msg "Stopping $name" "$name"
        start-stop-daemon --stop --quiet --oknodo --pidfile "$pid_file"
}

status () {
        status_of_proc -p $pid_file $logstash_bin "$name"
}

case $1 in
        start)
                if status; then exit 0; fi
                start
                ;;
        stop)
                stop
                ;;
        reload)
                stop
                start
                ;;
        restart)
                stop
                start
                ;;
        status)
                status && exit 0 || exit $?
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|reload|status}"
                exit 1
                ;;
esac
exit 0
